acount/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('signup_perform', views.signup_perform, name='signup_perform'),
    path('otp', views.otp, name='otp'),
    path('otp_perform', views.otp_perform, name='otp_perform'),
    path('user_login', views.user_login, name='user_login'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('for_otp', views.for_otp, name='for_otp'),
    path('forget_password_action', views.forget_password_action, name='forget_password_action'),
    path('forget_otp', views.forget_otp, name='forget_otp'),
    path('new_password', views.new_password, name='new_password'),
    path('category_search/<int:uid>', views.category_search, name='category_search'),
    path('search', views.search, name='search'),
    path('price_filter', views.price_filter, name='price_filter'),
    path('view_product/<int:pid>', views.view_product, name='view_product'),
    path('userprofile', views.userprofile, name='userprofile'),  # Updated URL pattern
    path('edit_profile', views.edit_profile, name='edit_profile'),  #  URL pattern
    path('edit_profileaction', views.edit_profileaction, name='edit_profileaction'), 
    path('log_out', views.log_out, name='log_out'),
    path('login_perform', views.login_perform, name='login_perform'),
]

basket/urls.py
from django.urls import path

from . import views
from .views import update_product_quantity

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/<int:product_id>/', views.basket_delete, name='basket_delete'),
    path('update/<int:product_id>/', update_product_quantity, name='update_product_quantity'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add_to_wishlist/<int:id>', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:id>', views.remove_from_wishlist, name='remove_from_wishlist'),
   
]

jq_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("acount.urls")),
    path('admin_sid/', include('admin_sid.urls')),
    path('basket/', include('basket.urls',namespace='basket')),
    path('payment/', include('payment.urls',namespace='payment')),
    path('orders/', include('orders.urls',namespace='orders')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from . import views
from .views import BasketView
app_name = 'payment'


urlpatterns = [
    path('payment/address/', BasketView, name='basket_view'),
    path('order_placed/', views.order_placed, name='order_placed'),
    path('BasketView/', views.BasketView, name='BasketView'),
    path('address/', views.address, name='address'),
    path('add_address/', views.add_address, name='add_address'),    
    path('edit_address/<int:aid>', views.edit_address, name='edit_address'),    
    path('address_active/<int:aid>', views.address_active, name='address_active'),    
    path('edit_product_action', views.edit_product_action, name='edit_product_action'),    
    path('oreder_view', views.oreder_view, name='oreder_view'),    
    path('upi_paypal_com', views.upi_paypal_com, name='upi_paypal_com'),    
    path('order/<int:order_id>/',views.order_detail, name='order_detail'),  
    path('order/<int:order_id>/cancel/', views.order_cancel, name='cancel_order'), 
    path('delete_address/<int:aid>', views.delete_address, name='delete_address'),    
]
 

basket/models.py
from decimal import Decimal
from django.db import models
from django.contrib.auth.models import User
from admin_sid.models import Product


# Create your models here.
class WishItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def get_subtotal_price(self):
        return sum(item.subtotal_price for item in self.items.all())

    @property
    def subtotal_price(self):
        print(
            f"Calculating subtotal for {self.product.title}: Quantity: {self.quantity}, Price: {self.product.price}"
        )
        return self.quantity * self.product.price


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)

    # Inside the Cart model
    def get_total_price(self):
        subtotal = self.get_subtotal_price()
        shipping_price = Decimal(str(self.get_shipping_price()))  # Convert to Decimal
        total = subtotal + shipping_price
        print(f"Cart total: {total}")
        return total

    def get_subtotal_price(self):
        subtotal = sum(item.subtotal_price for item in self.items.all())
        print(f"Calculated subtotal: {subtotal}")
        return subtotal

    def get_shipping_price(self):
        # Convert the shipping price to Decimal
        return Decimal('11.5')

    def print_cart_items(self):
        for item in self.items.all():
            print(
                f"Product: {item.product.title}, Quantity: {item.quantity}, Price: {item.product.price}, Subtotal: {item.subtotal_price}"
            )

    # Inside the Cart model
    def add_item_to_db(self, product, qty):
        cart_item, created = CartItem.objects.get_or_create(
            user=self.user, product=product, defaults={"quantity": qty}
        )

        if not created:
            cart_item.quantity += qty
            cart_item.save()

        self.items.add(cart_item)  # Add the cart item to the items relationship

    def update_item_in_db(self, product, qty):
        cart_item = CartItem.objects.get(user=self.user, product=product)
        cart_item.quantity = qty
        cart_item.save()

    def delete_item_from_db(self, product):
        CartItem.objects.filter(user=self.user, product=product).delete()

    
    def clear_cart_in_db(self):
        # Assuming you have a related manager called 'items'
        self.items.all().delete()

    def save_to_db(self):
        self.save()

    def __iter__(self):
        return iter(self.items.all())

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from admin_sid.models import Product
from basket.models import CartItem, WishItem
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from .models import Cart  # Import your Cart model
from basket.models import Cart
from .basket import Basket
from .models import Cart, CartItem
from django.views.decorators.http import require_POST


from decimal import Decimal

@login_required
def basket_summary(request):
    basket_instance = Basket(request)
    user = request.user
    cart, created = Cart.objects.get_or_create(user=user)

    cart = Cart.objects.get(user=request.user)

    # Calculate subtotal and shipping price
    cart_total = cart.get_total_price()
    subtotal = cart.get_subtotal_price()
    shipping_price = cart.get_shipping_price()
    
    # Calculate the total by adding subtotal and shipping price
    total = subtotal + shipping_price

    # Pass data to the template
    context = {
        'cart': cart,
        'cart_total': cart_total,
        'subtotal': subtotal,
        'shipping_price': shipping_price,
        'total': total,
    }
    print('the subtotal is',subtotal)
    return render(request, "basket/summary.html", context)



@login_required
def basket_add(request):
    basket = Basket(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        product_qty = int(request.POST.get("productqty"))
        product = get_object_or_404(Product, id=product_id)
        if product.stock >= product_qty:
            basket.add(product=product, qty=product_qty)
            basketqty = basket.__len__()
            response = JsonResponse({"qty": basketqty})
            return response


@login_required
@require_POST
def basket_delete(request, product_id):
    if request.headers.get("x-requested-with") == "XMLHttpRequest":
        basket = Basket(request)
        product = Product.objects.get(id=product_id)
        basket.delete(product)

        basket_qty = len(basket)
        basket_subtotal = basket.get_subtotal_price()

        response_data = {
            "qty": basket_qty,
            "subtotal": basket_subtotal,
        }
        return JsonResponse(response_data)
    else:
        return JsonResponse({"error": "Invalid request"})


@login_required
def update_product_quantity(request, product_id):
    user = request.user
    cart, created = Cart.objects.get_or_create(user=user)
    product = get_object_or_404(Product, id=product_id)

    if request.method == "POST":
        new_quantity = int(request.POST.get("productqty", 1))
        if new_quantity <= product.stock:
            cart.update_item_in_db(product, new_quantity)
            try:
                cart_item = cart.items.get(product=product)
                updated_qty = cart_item.quantity
            except CartItem.DoesNotExist:
                updated_qty = 0

            data = {
                "success": True,
                "qty": updated_qty,
                "productStock": product.stock,
                "subtotal": cart.get_subtotal_price(),
                "total": cart.get_total_price(),
                "productquantity": updated_qty,
            }
        else:
            data = {
                "success": False,
                "error": "Not enough stock available.",
            }

        return JsonResponse(data)

    return render(request, "basket/update_quantity.html", {"product": product})


def add_to_wishlist(request, id):
    product = Product.objects.get(id=id)
    wish_item, created = WishItem.objects.get_or_create(
        user=request.user, product=product
    )
    if created:
        return redirect("home")
    else:
        return redirect("basket:wishlist")


def wishlist(request):
    basket = Basket
    product = Product.objects.all()
    wish_items = WishItem.objects.filter(user=request.user)
    context = {
        "wish_items": wish_items,
        "product": product,
        "basket": basket,
    }
    return render(request, "basket/wishlist.html", context)


def remove_from_wishlist(request, id):
    try:
        item_to_remove = WishItem.objects.get(id=id)
        item_to_remove.delete()
        return redirect("basket:wishlist")
    except WishItem.DoesNotExist:
        return redirect("basket:wishlist")

templates/basket/summary.html
{% extends "app/base.html" %}
{% load static %}
{% block title %}
Shopping Cart
{% endblock title %}
{% block main-content %}


<div class="container">
  <div class="col-12">
    <h1 class="h2">Your Basket</h1>
  </div>
  <div class="col-12">
    <p>Manage your <b>items</b> in your basket</p>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row g-3">
    <div class="d-flex d-flex-inline">
      <div class="pe-3">Order</div>
      <div class="dropdown">
        <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink"
          data-bs-toggle="dropdown" aria-expanded="false">
          Shipping options
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-down"
            viewBox="0 0 16 16">
            <path fill-rule="evenodd"
              d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
          </svg>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownLink">
          <li class="item small">Next day delivery</li>
          <li class="item small">Premium delivery</li>
        </ul>
      </div>
    </div>

    <div class="col-12">
      <div class="product-box">
        <!-- Debugging Code -->
        <!-- Debugging Code -->

        {% for cart_item in basket.items.all %}
        <div class="product-item card mb-3 border-0" data-index="{{ cart_item.product.id }}">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              <img class="img-fluid mx-auto d-block" alt="Product Image" src="{{ cart_item.product.image1.url }}" />
            </div>
            <div class="col-md-10">
              <div class="card-body p-3">
                <a class="text-decoration-none text-reset" href="{{ cart_item.product.get_absolute_url }}">
                  <h5 class="card-title">{{ cart_item.product.title }}</h5>
                </a>
                <p class="card-text">₹{{ cart_item.product.price }}</p>
                <div class="flex items-center border-gray-100">
                  <div class="relative flex">
                    <button type="button" id="decrement-{{ cart_item.product.id }}"
                      data-index="{{ cart_item.product.id }}"
                      class="bg-secondary rounded hover:bg-gray-600 text-white font-semibold py-2 px-3 rounded-l-full decrement-button">-</button>
                    <input id="select-{{ cart_item.product.id }}" type="number" class="p-2" style="max-width: 80px;"
                      min="1" step="1" value="{{ cart_item.quantity }}">
                    <button type="button" id="increment-{{ cart_item.product.id }}"
                      data-index="{{ cart_item.product.id }}"
                      class="bg-secondary rounded hover:bg-gray-600 text-white font-semibold py-2 px-3 rounded-r-full increment-button">+</button>
                  </div>

                  <button type="button" class="delete-button btn btn-danger mt-2"
                    data-index="{{ cart_item.product.id }}">Delete</button>



                </div>
              </div>
            </div>
          </div>

          {% empty %}
          <h1>No Product in cart</h1>

          {% endfor %}
        </div>
      </div>

      {% if basket|length != 0 %}
      <!-- Use 'cart' instead of 'basket' -->
      <div class="col-12 bg-light p-3 d-flex flex-column justify-content-end align-items-end">
        <div class="text-end">
          <div class="">Sub Total: <span class="fw-bold">₹</span>
            <div id="subtotal" class="d-inline-flex fw-bold">{{cart_total}}</div>
          </div>
          <div id="">Shipping <span class="small">(Next day delivery)</span>: <span class="fw-bold">₹{{ shipping_price }}</span></div>

          <div id="total">Total: ₹{{ total }}</div>

          <div class="d-grid gap-2 mt-3">
            <a role="button" href="{% url 'payment:BasketView' %}" class="btn btn-success fw-bold"
              type="button">Checkout</a>
            <button class="btn btn-light" type="button">Save for later</button>
          </div>
        </div>
      </div>
      {% endif %}


    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script>
    // Delete Item
    $(document).on("click", ".delete-button", function (e) {
      e.preventDefault();
      var prodId = $(this).data("index");

      $.ajax({
        type: "POST",
        url: '{% url "basket:basket_delete" product_id=0 %}'.replace(0, prodId),
        data: {
          productid: prodId,
          csrfmiddlewaretoken: "{{ csrf_token }}",
          action: "post",
        },

        success: function (json) {
          // Alert moved outside the if-else block
          alert("Are you sure?");
          if (json.qty <= 0) {
            total = 0;
            subtotal = 0;
          } else {
            total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
            subtotal = json.subtotal;
          }
          
          window.location.reload();
          document.getElementById("subtotal").innerHTML = json.subtotal;
          document.getElementById("basket-qty").innerHTML = json.qty;
          document.getElementById("total").innerHTML = total;

        },


        error: function (xhr, errmsg, err) {
          console.error("Error occurred:", errmsg, err);
          // Handle errors if needed
        },

      });
    });


    // Update Item
    $(document).ready(function () {
      // Handle the increment button click
      $(document).on('click', '.increment-button', function () {
        updateQuantity($(this), 1);
      });

      // Handle the decrement button click
      $(document).on('click', '.decrement-button', function () {
        updateQuantity($(this), -1);
      });

      function updateQuantity(button, quantityChange) {
        const productId = button.data('index');
        const quantityInput = $('#select-' + productId);
        const currentQuantity = parseInt(quantityInput.val());
        const newQuantity = currentQuantity + quantityChange;

        if (newQuantity >= 1 && newQuantity <= 100) {
          $.ajax({
            type: 'POST',
            url: '{% url "basket:update_product_quantity" product_id=0 %}'.replace(0, productId),
            data: {
              productid: productId,
              productqty: newQuantity,
              csrfmiddlewaretoken: '{{ csrf_token }}',
              action: 'post',
            },
            success: function (json) {
              console.log("AJAX Response:", json);
              window.location.reload();
              console.log(json);
              if (json.qty <= json.productStock) {
                document.getElementById('basket-qty').innerHTML = json.qty;
                document.getElementById('subtotal').innerHTML = json.subtotal;
                document.getElementById('cart-total').innerHTML = json.total;
                document.getElementById('total').innerHTML = json.total;
                document.getElementById('productquantity').innerHTML = json.productquantity;
              } else {
                alert('Not enough stock!');
              }
            },
            error: function (xhr, errmsg, err) {
              window.location.reload();

            }
          });
        } else {
          alert('Quantity must be between 1 and 100');
          quantityInput.focus();
        }
      }
    });

  </script>
  <script>
    $(document).ready(function () {
      // Handle the increment button click
      $(document).on('click', '.increment-button', function () {
        const productId = $(this).data('index');
        const quantityInput = $('#select-' + productId);
        const currentQuantity = parseInt(quantityInput.val());
        quantityInput.val(currentQuantity + 1);
      });

      // Handle the decrement button click
      $(document).on('click', '.decrement-button', function () {
        const productId = $(this).data('index');
        const quantityInput = $('#select-' + productId);
        const currentQuantity = parseInt(quantityInput.val());
        if (currentQuantity > 1) {  // Min quantity is 1
          quantityInput.val(currentQuantity - 1);
        }
      });
    });
  </script>


  {% endblock main-content %}

templates/basket/wishlist.html
{% extends "app/base.html" %}
{% load static %}
{% block title %}
Wishlist
{% endblock title %}

{% block main-content %}
<style>
    .cart-wrap {
        padding: 40px 0;
        font-family: 'Open Sans', sans-serif;
    }

    .main-heading {
        font-size: 19px;
        margin-bottom: 20px;
    }

    .table-wishlist table {
        width: 100%;
    }

    .table-wishlist thead {
        border-bottom: 1px solid #e5e5e5;
        margin-bottom: 5px;
    }

    .table-wishlist thead tr th {
        padding: 8px 0 18px;
        color: #484848;
        font-size: 15px;
        font-weight: 400;
    }

    .table-wishlist tr td {
        padding: 25px 0;
        vertical-align: middle;
    }

    .table-wishlist tr td .img-product {
        width: 72px;
        float: left;
        margin-left: 8px;
        margin-right: 31px;
        line-height: 63px;
    }

    .table-wishlist tr td .img-product img {
        width: 100%;
    }

    .table-wishlist tr td .name-product {
        font-size: 15px;
        color: #484848;
        padding-top: 8px;
        line-height: 24px;
        width: 50%;
    }

    .table-wishlist tr td.price {
        font-weight: 600;
    }

    .table-wishlist tr td .quanlity {
        position: relative;
    }

    .total {
        font-size: 24px;
        font-weight: 600;
        color: #8660e9;
    }

    .display-flex {
        display: flex;
    }

    .align-center {
        align-items: center;
    }

    .round-black-btn {
        border-radius: 25px;
        background: #212529;
        color: #fff;
        padding: 5px 20px;
        display: inline-block;
        border: solid 2px #212529;
        transition: all 0.5s ease-in-out 0s;
        cursor: pointer;
        font-size: 14px;
    }

    .round-black-btn:hover,
    .round-black-btn:focus {
        background: transparent;
        color: #212529;
        text-decoration: none;
    }

    .mb-10 {
        margin-bottom: 10px !important;
    }

    .mt-30 {
        margin-top: 30px !important;
    }

    .d-block {
        display: block;
    }

    .custom-form label {
        font-size: 14px;
        line-height: 14px;
    }

    .pretty.p-default {
        margin-bottom: 15px;
    }

    .pretty input:checked~.state.p-primary-o label:before,
    .pretty.p-toggle .state.p-primary-o label:before {
        border-color: #8660e9;
    }

    .pretty.p-default:not(.p-fill) input:checked~.state.p-primary-o label:after {
        background-color: #8660e9 !important;
    }

    .main-heading.border-b {
        border-bottom: solid 1px #ededed;
        padding-bottom: 15px;
        margin-bottom: 20px !important;
    }

    .custom-form .pretty .state label {
        padding-left: 6px;
    }

    .custom-form .pretty .state label:before {
        top: 1px;
    }

    .custom-form .pretty .state label:after {
        top: 1px;
    }

    .custom-form .form-control {
        font-size: 14px;
        height: 38px;
    }

    .custom-form .form-control:focus {
        box-shadow: none;
    }

    .custom-form textarea.form-control {
        height: auto;
    }

    .mt-40 {
        margin-top: 40px !important;
    }

    .in-stock-box {
        background: #ff0000;
        font-size: 12px;
        text-align: center;
        border-radius: 25px;
        padding: 4px 15px;
        display: inline-block;
        color: #fff;
    }

    .trash-icon {
        font-size: 20px;
        color: #212529;
    }
</style>

<div class="cart-wrap">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="main-heading mb-10">My wishlist</div>
                {% if wish_items %}
                <div class="table-wishlist">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <thead>
                            <tr>
                                <th width="45%">Product Name</th>
                                <th width="15%">Unit Price</th>
                                <th width="15%">Stock Status</th>
                                <th width="15%"></th>
                                <th width="10%"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in wish_items %}
                            <tr>
                                <td width="45%">
                                    <div class="display-flex align-center">
                                        <div class="img-product">
                                            <img src="{{ item.product.image1.url }}" alt="{{ item.product.title }}">
                                        </div>
                                        <div class="name-product">
                                            {{ item.product.title }}
                                        </div>
                                    </div>
                                </td>
                                <td width="15%" class="price">{{ item.product.price }}</td>
                                {% if item.product.stock > 0 %}
                                <td width="15%"><span class="in-stock-box">In Stock</span></td>
                                <!-- Add to Cart button -->
                                {% if not item in basket %}
                                <td width="15%">
                                    <button type="button" class="round-black-btn small-btn add-to-cart-button"
                                        data-productid="{{ item.product.id }}">Add to Cart
                                    </button>
                                    <!-- Debug statement -->
                                </td>
                                {% else %}
                                <td width="15%">
                                    <a href="{% url 'basket:basket_summary' %}">
                                        <button type="button" class="round-black-btn small-btn">Go to Cart</button>
                                    </a>
                                    <!-- Debug statement -->
                                </td>
                                {% endif %}
                                {% else %}
                                <td width="15%"><span class="in-stock-box">Out of Stock</span></td>
                                <td width="15%"> <!-- Display a message or placeholder for out-of-stock items --> </td>
                                {% endif %}
                                <td width="10%" class="text-center">
                                    <a href="{% url 'basket:remove_from_wishlist' item.id %}" class="trash-icon"><i
                                            class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>
                            {% endfor %}


                        </tbody>
                    </table>
                </div>
                {% else %}
                <p>Your wishlist is empty.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- JavaScript for handling Add to Cart button click -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script>
    $(document).ready(function () {
        $(".add-to-cart-button").click(function () {
            var productId = $(this).data("productid");

            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    productid: productId,
                    productqty: 1,
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {
                    window.location.reload();
                    document.getElementById("basket-qty").innerHTML = json.qty;
                },
                error: function (xhr, errmsg, err) {
                    // Handle error if needed
                }
            });
        });
    });
</script>
{% endblock main-content %}