acount/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('signup_perform', views.signup_perform, name='signup_perform'),
    path('otp', views.otp, name='otp'),
    path('otp_perform', views.otp_perform, name='otp_perform'),
    path('user_login', views.user_login, name='user_login'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('for_otp', views.for_otp, name='for_otp'),
    path('forget_password_action', views.forget_password_action, name='forget_password_action'),
    path('forget_otp', views.forget_otp, name='forget_otp'),
    path('new_password', views.new_password, name='new_password'),
    path('category_search/<int:uid>', views.category_search, name='category_search'),
    path('search', views.search, name='search'),
    path('price_filter', views.price_filter, name='price_filter'),
    path('view_product/<int:pid>', views.view_product, name='view_product'),
    path('userprofile', views.userprofile, name='userprofile'),  # Updated URL pattern
    path('edit_profile', views.edit_profile, name='edit_profile'),  #  URL pattern
    path('edit_profileaction', views.edit_profileaction, name='edit_profileaction'), 
    path('log_out', views.log_out, name='log_out'),
    path('login_perform', views.login_perform, name='login_perform'),
]

jq_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("acount.urls")),
    path('admin_sid/', include('admin_sid.urls')),
    path('basket/', include('basket.urls',namespace='basket')),
    path('payment/', include('payment.urls',namespace='payment')),
    path('orders/', include('orders.urls',namespace='orders')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('add/',views.add, name='add'),
    path('dashboard/',views.dashboard, name='dashboard'),
    
]

payment/urls.py
from django.urls import path

from . import views
from .views import BasketView
app_name = 'payment'


urlpatterns = [
    path('payment/address/', BasketView, name='basket_view'),
    path('order_placed/', views.order_placed, name='order_placed'),
    path('BasketView/', views.BasketView, name='BasketView'),
    path('address/', views.address, name='address'),
    path('add_address/', views.add_address, name='add_address'),    
    path('edit_address/<int:aid>', views.edit_address, name='edit_address'),    
    path('address_active/<int:aid>', views.address_active, name='address_active'),    
    path('edit_product_action', views.edit_product_action, name='edit_product_action'),    
    path('oreder_view', views.oreder_view, name='oreder_view'),    
    path('upi_paypal_com', views.upi_paypal_com, name='upi_paypal_com'),    
    path('order/<int:order_id>/',views.order_detail, name='order_detail'),  
    path('order/<int:order_id>/cancel/', views.order_cancel, name='cancel_order'), 
    path('delete_address/<int:aid>', views.delete_address, name='delete_address'),    
]
 

orders/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from admin_sid.models import Product

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='order_user', null=True, blank=True)
    full_name = models.CharField(max_length=50, null=True, blank=True)
    address1 = models.CharField(max_length=250, null=True, blank=True)
    address2 = models.CharField(max_length=250, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    post_code = models.CharField(max_length=20, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, null=True, blank=True)
    total_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    order_key = models.CharField(max_length=200, null=True, blank=True)
    billing_status = models.CharField(max_length=10,)

    # New field for order status
    ORDER_STATUS_CHOICES = [
        ('confirmed', 'Order Confirmed'),
        ('shipped', 'Shipped'),
        ('out_for_delivery', 'Out for Delivery'),
        ('delivered', 'Delivered'),
        # Add more statuses as needed
    ]

    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='confirmed')

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return f"{self.created} - {self.status}"

    @classmethod
    def get_user_order_status(cls, user):
        """
        Get the status of the latest order for a specific user.
        """
        latest_order = cls.objects.filter(user=user).order_by('-created').first()
        if latest_order:
            return latest_order.status
        return None


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

payment/models.py
from django.db import models    
from django.contrib.auth.models import User

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50, null=True, blank=True)
    address1 = models.CharField(max_length=250, null=True, blank=True)
    address2 = models.CharField(max_length=250, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    post_code = models.CharField(max_length=20, null=True, blank=True)
    flag = models.BooleanField(default=False)

    
    class Meta:
        verbose_name_plural = "Addresses"

    def __str__(self):
        return f"{self.full_name}'s Address"

payment/forms.py
# forms.py
from django import forms
from orders.models import Order  # Make sure to import the Order model

class AddressForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['full_name', 'address1', 'phone', 'city', 'post_code']

orders/views.py
from django.shortcuts import render
from django.http.response import JsonResponse

from basket.basket import Basket
from .models  import Order, OrderItem

# Create your views here.   

def add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':

        order_key = request.POST.get('order_key')
        user_id = request.user.id
        baskettotal = basket.get_total_price()

        # Check if order exists
        
        order = Order.objects.create(user_id=user_id, full_name='name', address1='add1',
                            address2='add2', total_paid=baskettotal, order_key=order_key)
        order_id = order.pk

        for item in basket:
            OrderItem.objects.create(order_id=order_id, product=item['product'], price=item['price'], quantity=item['qty'])

        response = JsonResponse({'success': 'success'})
        return response


def dashboard(request):
    return render(request,'account/dashboard/dashboard.html')

payment/views.py
import json
from django.shortcuts import get_object_or_404
from admin_sid.models import Product
from basket.basket import Basket
from orders.models import Order, OrderItem
from payment.models import Address
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
import uuid
from datetime import datetime


def order_placed(request):
    return render(request, "payment/orderplaced.html")


def generate_order_key():
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    unique_id = str(uuid.uuid4().hex)[:6]  # Use the first 6 characters of a UUID
    order_key = f"ORDER-{timestamp}-{unique_id}"
    return order_key


@login_required
def address(request):
    billing_address = get_object_or_404(Address, user=request.user, flag=True)

    if request.method == "POST":
        basket = Basket(request)

        if billing_address:
            paymentmethod = request.POST.get("paymentMethod")
            total_paid = basket.get_total_price()
            order_key = generate_order_key()

            for item in basket.items:
                product = item.product
                if item.quantity > product.stock:
                    basket.clear()
                    billing_address = Address.objects.filter(user=request.user)
                    return render(
                        request,
                        "payment/address.html",
                        {
                            "message": f"Insufficient stock for {product.title}",
                            "billing_address": billing_address,
                        },
                    )

            if paymentmethod == "cod":
                order = Order.objects.create(
                    user=request.user,
                    full_name=billing_address.full_name,
                    address1=billing_address.address1,
                    address2=billing_address.address2,
                    city=billing_address.city,
                    phone=billing_address.phone,
                    post_code=billing_address.post_code,
                    total_paid=total_paid,
                    order_key=order_key,
                    billing_status=paymentmethod,
                )

                order_id = order.pk

                for item in basket.items:
                    OrderItem.objects.create(
                        order=order,
                        product=item.product,
                        price=item.product.price,  # Update this line with the correct attribute
                        quantity=item.quantity,
                    )
                    product = item.product
                    product.stock -= item.quantity
                    product.save()

                basket.clear()

                return render(request, "payment/orderplaced.html")
            else:
                # Handle other payment methods if needed
                return render(request, "payment/UPI.html")

    billing_address = Address.objects.filter(user=request.user)
    return render(request, "payment/address.html", {"billing_address": billing_address})


def upi_paypal_com(request):
    billing_address = get_object_or_404(Address, user=request.user, flag=True)

    if request.method == "POST":
        basket = Basket(request)

        if billing_address:
            body = json.loads(request.body)
            paymentmethod = body.get("paymentmethod")
            print(paymentmethod)
            total_paid = basket.get_total_price()
            order_key = generate_order_key()

            for item in basket:
                product = item.product
                if item.quantity > product.stock:
                    basket.clear()
                    billing_address = Address.objects.filter(user=request.user)
                    return render(
                        request,
                        "payment/address.html",
                        {
                            "message": f"Insufficient stock for {product.title}",
                            "billing_address": billing_address,
                        },
                    )

            # Continue with the rest of your logic
            # ...

            # Continue with the rest of your logic
            # ...

            order = Order.objects.create(
                user=request.user,
                full_name=billing_address.full_name,
                address1=billing_address.address1,
                address2=billing_address.address2,
                city=billing_address.city,
                phone=billing_address.phone,
                post_code=billing_address.post_code,
                total_paid=total_paid,
                order_key=order_key,
                billing_status=paymentmethod,
            )

            order_id = order.pk

            for item in basket:
                OrderItem.objects.create(
                    order=order,
                    product=item.product,  # Use item.product instead of item["product"]
                    price=item.subtotal_price,  # Adjust this if needed
                    quantity=item.quantity,  # Use item.quantity instead of item["qty"]
                )
                product = item.product
                product.stock -= item.quantity  # Use item.quantity instead of item["qty"]
                product.save()

            basket.clear()
    return JsonResponse("Payment completed", safe=False)



def address_active(request, aid):
    billing_address = Address.objects.get(id=aid)
    act_address = Address.objects.filter(flag=True).first()
    if act_address:
        act_address.flag = False
        act_address.save()
    if billing_address:
        billing_address.flag = True
        billing_address.save()

    messages.success(request, "Address set to default")
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def add_address(request):
    if request.user.is_authenticated:
        return render(request, "payment/home.html")
    else:
        return redirect("home")


def edit_address(request, aid):
    if request.user.is_authenticated:
        address = Address.objects.get(id=aid)
        return render(request, "payment/edit_address.html", {"address": address})
    else:
        return redirect("home")


def edit_product_action(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            id = request.POST.get("id")
            custname = request.POST.get("custName", "")
            address1 = request.POST.get("custAdd", "")
            phone = request.POST.get("phone", "")
            state = request.POST.get("state", "")
            pincode = request.POST.get("pincode", "")

            address = Address.objects.get(id=id)

            address.full_name = custname
            address.address1 = address1
            address.phone = phone
            address.city = state
            address.post_code = pincode

            # Save the updated product
            address.save()
            billing_address = Address.objects.filter(user=request.user)
            return render(
                request, "payment/address.html", {"billing_address": billing_address}
            )
            # return HttpResponseRedirect(request.META['HTTP_REFERER'])
        else:
            return redirect("address")
    else:
        return redirect("home")


@login_required
def delete_address(request, aid):
    address = Address.objects.get(id=aid)
    if address.user != request.user:
        messages.error(request, "You don't have permission to delete this address.")
        return redirect("payment:address")
    address.delete()
    messages.success(request, "Address deleted successfully.")

    return redirect("payment:BasketView")


@login_required
def BasketView(request):
    billing_address = Address.objects.filter(user=request.user)
    if request.method == "POST":
        custname = request.POST.get("custName", "")
        address1 = request.POST.get("custAdd", "")
        phone = request.POST.get("phone", "")
        state = request.POST.get("state", "")
        pincode = request.POST.get("pincode", "")
        addresses = Address.objects.all()
        if addresses:
            try:
                active_address = addresses.get(flag=True)
                active_address.flag = False
                active_address.save()
            except:
                pass

        # Ensure the user is properly authenticated
        if request.user.is_authenticated:
            user = request.user

            Address.objects.create(
                user=user,
                full_name=custname,
                address1=address1,
                phone=phone,
                city=state,
                post_code=pincode,
                flag=True,
            )

    return render(request, "payment/address.html", {"billing_address": billing_address})


# -----------------------------------------
def oreder_view(request):
    orders = Order.objects.filter(user=request.user)
    order_statuses = {order.id: order.status for order in orders}
    return render(
        request,
        "payment/orders.html",
        {"orders": orders, "order_statuses": order_statuses},
    )


def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order_items = OrderItem.objects.filter(order=order)
    return render(
        request,
        "payment/order_detail.html",
        {"order": order, "order_items": order_items},
    )


def order_cancel(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    if request.method == "POST":
        order_items = order.items.all()

        for order_item in order_items:
            product = order_item.product
            product.stock += order_item.quantity
            product.save()

        order.status = "canceled"
        order.save()

templates/payment/UPI.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
UPI
{% endblock title %}

{% block main-content %}

<div class="container">
    <div class="col-12">
        <h1 class="h2">Delivery Options</h1>
    </div>
    <div class="col-12">
        <p>Please select your delivery option</p>
    </div>
    <hr />
</div>

<div class="container">
    <div class="row g-3">
        <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
            <div class="d-flex bd-highlight ms-0">
                <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">₹</span><span id="sub_total"
                        class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
            </div>
            <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">₹</span><span id="delivery_price"
                        class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
            </div>
            <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">₹</span><span id="total"
                        class="fw-bold h5">{{basket.get_total_price}}</span></div>
            </div>
        </div>
        <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
            <div id="paypal-button-container"></div>
        </div>
    </div>
</div>
<script src="https://www.paypal.com/sdk/js?client-id=Aes7OpyAgtqoxh-dzHIW9LW5nUeVGUPpYVFgmmPL-8IV_j_N5oIQN_NldCqoLz6BhbK7JlvcO3xiQDB7"></script>
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');



    function initPayPalButton() {
        paypal.Buttons({
            style: {
                shape: 'rect',
                color: 'gold',
                layout: 'vertical',
                label: 'paypal',

            },
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        "amount": {
                            "currency_code": "USD",
                            "value": '{{basket.get_total_price}}'
                        }
                    }]
                });
            },
            onApprove: function (data) {
                var url = '{% url "payment:upi_paypal_com" %}'
                return fetch(url, {
                    method: 'POST',
                    headers: {
                        'content-type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify({
                        paymentmethod: 'bank'
                    })
                }).then(function () {
                    location.href = '{% url "payment:order_placed" %}';
                })
            },
        }).render('#paypal-button-container');
    }
    initPayPalButton();

</script>

{% endblock %}

templates/payment/address.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
User Address
{% endblock title %}

{% block main-content %}

<div class="container shadow p-3 mb-5 bg-white rounded">
  <div class="row">
    <div class="col-md-8">
      <h2>Your Addresses</h2>

      <div class="col-md-12">
        {% for address in billing_address %}
        <div class="card d-flex justify-content-between align-items-center" style="width: 18rem; margin-bottom: 10px;">
          <div>

            <p><strong>Customer Name:</strong> {{ address.full_name }}</p>
            <p><strong>Email:</strong> {{ address.user.email }}</p>
            <p><strong>Address:</strong> {{ address.address1 }}</p>
            <p><strong>Address 2:</strong> {{ address.address2 }}</p>
            <p><strong>State:</strong> {{ address.city }}</p>
            <p><strong>Postcode:</strong> {{ address.post_code }}</p>
            <!-- Add more fields as needed -->
          </div>

          <div class="d-flex">
            <!-- Edit button -->
            <a href="{% url 'payment:edit_address' address.id  %}" class="btn btn-warning btn-sm">Edit</a>
            &nbsp;
            <!-- Delete button -->
            {% if not address.flag %}
            <a href="{% url 'payment:delete_address' address.id %}" class="btn btn-danger btn-sm">Delete</a>
            &nbsp;

            <a href="{% url 'payment:address_active' address.id  %}" class="btn btn-primary btn-sm">Make active</a>


            {% endif %}
          </div>
          <br>
        </div>
        {% endfor %}
        <a href="{% url 'payment:add_address' %}" class="btn btn-success btn-sm">Add Address</a>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Order Summary</h5>

          <!-- Display cart items -->
          <table class="table ">
            <thead>
              <tr>
                <th scope="col">Image</th>
                <th scope="col">Product Name</th>
                <th scope="col">Price</th>

              </tr>
            </thead>
            <tbody>
              {% for item in basket %}
              {% with product=item.product %}
              <tr>
                <!-- Small product image -->
                <td>
                  <img class="img-fluid mx-auto d-block" alt="Product Image" src="{{ product.image1.url }}"
                    style="max-width: 50px; max-height: 50px;">
                </td>

                <!-- Product details -->
                <td>
                  <p>{{ product.title }}</p>
                </td>

                <!-- Price -->
                <td>
                  <p> ₹{{ product.price }}</p>

                  <!-- Add your form here for delete action -->
                </td>
              </tr>
              {% endwith %}
              {% empty %}
              <tr>
                <td colspan="4">No items in the basket.</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <p>Subtotal: ${{ basket.get_subtotal_price }}</p>
          <p>Shipping Price: ${{basket.shipping_price}}</p>
          <p>Total: ${{ basket.get_total_price }}</p>

          <!-- Payment method radio buttons -->
          <form action="{% url 'payment:address' %}" method="post">
            {% csrf_token %}
            <div class="form-check">
              <input type="radio" class="form-check-input" id="bankPayment" name="paymentMethod" value="UPI">
              <label class="form-check-label" for="bankPayment">UPI</label>
            </div>
            <div class="form-check">
              <input type="radio" class="form-check-input" id="codPayment" name="paymentMethod" value="cod">
              <label class="form-check-label" for="codPayment">Cash on Delivery</label>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Place Order</button>
          </form>
          <!-- Coupon input field -->
          <br>
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Coupon Code" aria-label="Coupon Code"
              aria-describedby="applyCoupon">
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="button" id="applyCoupon">Apply Coupon</button>
            </div>
          </div>

          <!-- Place Order button -->
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/payment/edit_address.html
{% extends "app/base.html" %}
{% load static %}
{% block title %}
  Shopping Cart
{% endblock title %} 

{% block main-content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-4 shadow p-3 mb-5 bg-white rounded">
    <form method="post" action="{% url 'payment:edit_product_action' %}">

    {% csrf_token %}
    <h3 class="mb-3">Billing address</h3>
    <!-- Error messages in this element -->
   <input type="hidden" name="flot" value="{{address.id}}">
    <div class="row g-3">
      <div class="col-md-7">
        <label for="custName" class="form-label">Customer Name</label>
        <input type="text" class="form-control" name="custName" id="custName" value="{{address.full_name}}" required>
        <div class="invalid-feedback">
          Please enter a valid customer name.
        </div>
      </div>
     
      <!-- Add similar styling for the rest of the form fields -->
      <div class="col-12">
        <label for="address" class="form-label">Address</label>
        <input type="text" class="form-control" id="custAdd" name="custAdd" value="{{address.address1}}" required>
        <div class="invalid-feedback">
            Please enter your shipping address.
        </div>
      </div>
      <div class="col-12">
        <label for="address2" class="form-label">Phone Number</label>
        <input type="text" class="form-control" id="custAdd2" name="phone" value="{{address.phone}}" >
      </div>
     
      <div class="col-mod-5">
        <label for="country" class="form-label">State</label>
        <select class="form-select" name="state" id="country" required value="{{address.city}}">
            <option value="state">Choose..</option>
            <option>kerala</option>
        </select>
        <div class="invalid-feedback">
            Please select a valid State.
        </div>
      </div>
      <!-- ... -->

      <div class="col-md-3">
        <label for="postCode" class="form-label">Pincode</label>
        <input type="text" class="form-control" id="postCode" name="pincode" required value="{{address.post_code}}" required>
      </div>
        <br>
        <button type="submit" class="btn btn-primary" >Save </button>
  </form>

</div>
</div>
  
  <script>
    var STRIPE_PUBLISHABLE_KEY = '{{STRIPE_PUBLISHABLE_KEY}}'
    var CSRF_TOKEN = '{{ csrf_token }}';
  </script>
  <script src="https://js.stripe.com/v3/"></script>
  <script src="{% static 'payment/index.js' %}" data-rel-js></script>
{% endblock %}

templates/payment/order_detail.html
<!-- payment/templates/payment/order_detail.html -->
{% extends "app/base.html" %}
{% load static %}

{% block title %}
    Order Detail - {{ order.id }}
{% endblock title %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block main-content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card order-detail-card">
                <div class="card-body">

                    <p>Order Date: {{ order.created }}</p>
                    <p>Total Amount: ₹{{ order.total_paid }}</p>

                    <h6 class="mt-4">Order Items:</h6>
                    <ul>
                        {% for item in order_items %}
                            <li>
                                <img src="{{ item.product.image1.url }}" alt="{{ item.product.name }}" style="max-width: 50px; max-height: 50px;">
                                {{ item.product.name }} - ₹{{ item.product.price }} (Quantity: {{ item.quantity }})
                            </li>
                        {% endfor %}
                    </ul>
                    <p>payment method:{{order.billing_status}}</p>
                    <p>Status: <span class="{% if order.status == 'canceled' %}text-danger{% endif %}">{{ order.get_status_display }}</span></p>

                    {% if order.status == 'confirmed' %}
                        <form method="post" action="{% url 'payment:cancel_order' order.id %}">
                            {% csrf_token %}
                            <input type="submit" id="cancel-order" onclick="return confirm('Do you want to delete?');" value="Cancel Order" class="btn btn-danger">
                        </form>
                    {% elif order.status == 'canceled' %}
                        <p class="text-danger">This order has been canceled.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <script>
    // Assume orderStatus is a variable passed from your server-side code with the initial order status
    var orderStatus = "{{ order.status }}";

    // Update the status display on page load
    updateStatusDisplay(orderStatus);

    function updateStatusDisplay(status) {
        var statusElement = document.getElementById("order-status");
        if (statusElement) {
            statusElement.innerHTML = 'Status: <span class="' + (status === 'canceled' ? 'text-danger' : '') + '">' + status + '</span>';
        }
    }

    // Retrieve the saved order status from local storage and update the display
    var savedStatus = localStorage.getItem('orderStatus_' + {{ order.id }});
    if (savedStatus) {
        updateStatusDisplay(savedStatus);
    }
</script> -->

{% endblock %}